# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'Hello-Lynx-OC' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Hello-Lynx-OC

# end

source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

target 'Hello-Lynx-OC' do
  pod 'Lynx', '3.2.0-rc.0', :subspecs => [
    'Framework',
  ]

  pod 'GoogleMaps', '7.3.0'
  pod 'Google-Maps-iOS-Utils', '4.2.2'

  pod 'PrimJS', '2.11.1-rc.1', :subspecs => ['quickjs', 'napi']

  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.2.0-rc.0', :subspecs => [
      'Image',
      'Log',
      'Http',
      'Devtool',
  ]

  pod 'DebugRouter', '5.0.6-alpha.2'

  # ImageService
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end
